// Package gateway defines a provider-neutral payment gateway abstraction so the
// checkout flow does not depend on any single provider (Midtrans, Xendit,
// Stripe, …). Module 08 (tenant portal) only needs checkout creation; webhook
// verification and parsing extend this interface in the payment-gateway module.
package gateway

import (
	"context"
	"time"
)

// CheckoutInput is the provider-neutral request to open a checkout session for a
// single bill. OrderID is generated by the caller (the service) so the system
// owns the external order reference end to end.
type CheckoutInput struct {
	OrderID    string
	BillNumber string
	BillID     string
	TenantID   string
	Amount     int
	Currency   string
	ReturnURL  string
}

// CheckoutResult is the normalized response from a provider's create-checkout
// call. RawResponse holds the provider's original JSON payload for audit.
type CheckoutResult struct {
	Provider              string
	ExternalOrderID       string
	ExternalTransactionID string
	CheckoutURL           string
	ExpiresAt             time.Time
	RawResponse           []byte
}

// Provider is the minimal contract a payment gateway must satisfy for the tenant
// Pay Now flow. Implementations must be safe for concurrent use.
type Provider interface {
	// Name returns the provider identifier stored on the transaction (e.g. "midtrans").
	Name() string
	// CreateCheckout opens a checkout session and returns its normalized result.
	CreateCheckout(ctx context.Context, in CheckoutInput) (*CheckoutResult, error)
}
